#!/usr/bin/env bash
set -euo pipefail

PROJECT_KEY="${1:-}"
TASK_KEY="${2:-}"

if [[ -z "$PROJECT_KEY" || -z "$TASK_KEY" ]]; then
  echo "Usage:"
  echo "  ./runners/attach_uploads_to_pm_context.sh <project_key> <task_key>"
  echo
  echo "Example:"
  echo "  ./runners/attach_uploads_to_pm_context.sh client-company-profile-demo CLIENT-1-001"
  exit 1
fi

if ! [[ "$PROJECT_KEY" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
  echo "ERROR: project_key must use lowercase letters, numbers, and dashes only."
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_DIR="$ROOT_DIR/projects/clients/$PROJECT_KEY"
TASK_FILE="$PROJECT_DIR/$TASK_KEY.md"
HANDOVER_FILE="$PROJECT_DIR/AGENT_HANDOVER.md"

if [[ ! -d "$PROJECT_DIR" ]]; then
  echo "ERROR: project directory not found: $PROJECT_DIR"
  exit 1
fi

if [[ ! -f "$TASK_FILE" ]]; then
  echo "ERROR: task file not found: $TASK_FILE"
  exit 1
fi

psql_rows() {
  docker exec -i ai_company_postgres psql \
    -U ai_company \
    -d ai_company \
    -t \
    -A \
    -F "|" \
    -v ON_ERROR_STOP=1 \
    -c "$1"
}

UPLOAD_ROWS="$(psql_rows "
SELECT
  id,
  original_filename,
  relative_path,
  COALESCE(mime_type, ''),
  COALESCE(size_bytes, 0),
  created_at
FROM project_uploads
WHERE project_key = '${PROJECT_KEY}'
ORDER BY id ASC;
")"

ATTACHMENT_BLOCK="$(mktemp)"

{
  echo
  echo "## Project Upload Attachments"
  echo
  echo "Generated by:"
  echo
  echo "    runners/attach_uploads_to_pm_context.sh $PROJECT_KEY $TASK_KEY"
  echo
  echo "Project:"
  echo
  echo "    $PROJECT_KEY"
  echo
  echo "Task:"
  echo
  echo "    $TASK_KEY"
  echo

  if [[ -z "$UPLOAD_ROWS" ]]; then
    echo "No uploaded files are currently linked to this project."
  else
    echo "Uploaded files linked to this project:"
    echo

    while IFS="|" read -r id original_filename relative_path mime_type size_bytes created_at; do
      [[ -z "${id:-}" ]] && continue
      echo "- Upload #$id"
      echo "  - File: $original_filename"
      echo "  - Path: $relative_path"
      echo "  - MIME: ${mime_type:-unknown}"
      echo "  - Size: $size_bytes bytes"
      echo "  - Uploaded at: $created_at"
    done <<< "$UPLOAD_ROWS"
  fi

  echo
  echo "Agent instruction:"
  echo
  echo "- PM agent should review the uploaded files before producing the requirement analysis."
  echo "- If a file cannot be read directly, mention it in the handover and ask Owner for clarification."
} > "$ATTACHMENT_BLOCK"

python3 - "$TASK_FILE" "$ATTACHMENT_BLOCK" << 'PY2'
from pathlib import Path
import sys

task_file = Path(sys.argv[1])
block_file = Path(sys.argv[2])

marker = "\n## Project Upload Attachments\n"
text = task_file.read_text()
block = block_file.read_text()

if marker in text:
    text = text.split(marker)[0].rstrip() + "\n"
task_file.write_text(text + block)
PY2

{
  echo
  echo "## Upload Context Attached for $TASK_KEY"
  echo
  echo "Upload context has been attached to:"
  echo
  echo "    $TASK_FILE"
  echo
  echo "Current uploaded files:"
  echo

  if [[ -z "$UPLOAD_ROWS" ]]; then
    echo "- No uploads found for project $PROJECT_KEY"
  else
    while IFS="|" read -r id original_filename relative_path mime_type size_bytes created_at; do
      [[ -z "${id:-}" ]] && continue
      echo "- #$id $original_filename"
      echo "  - $relative_path"
    done <<< "$UPLOAD_ROWS"
  fi
} >> "$HANDOVER_FILE"

rm -f "$ATTACHMENT_BLOCK"

"$ROOT_DIR/runners/log_event.sh" \
  "$PROJECT_KEY" \
  "$TASK_KEY" \
  "pm_agent" \
  "uploads_attached_to_pm_context" \
  "READY" \
  "planning_room" \
  "Project uploads attached to PM context" \
  "Uploaded project files were attached to PM intake context for $TASK_KEY."

echo "Upload context attached:"
echo "- Project: $PROJECT_KEY"
echo "- Task: $TASK_KEY"
echo "- Task file: $TASK_FILE"
echo "- Handover file: $HANDOVER_FILE"
