#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 AGENT_KEY TASK_KEY [--dry-run|--plan]"
  exit 1
fi

AGENT_KEY="$1"
TASK_KEY="$2"
MODE="${3:---dry-run}"

if [ "$MODE" != "--dry-run" ] && [ "$MODE" != "--plan" ]; then
  echo "Usage: $0 AGENT_KEY TASK_KEY [--dry-run|--plan]"
  exit 1
fi

psql_scalar() {
  docker exec ai_company_postgres psql -U ai_company -d ai_company -At -c "$1" | head -1 | tr -d '[:space:]'
}

TASK_ROW="$(docker exec ai_company_postgres psql -U ai_company -d ai_company -At -F $'\t' -c "
SELECT
  task_key,
  title,
  status,
  current_phase,
  assigned_agent_key,
  priority
FROM tasks
WHERE task_key='${TASK_KEY}'
LIMIT 1;
")"

if [ -z "$TASK_ROW" ]; then
  echo "SKIP: task not found: $TASK_KEY"
  exit 0
fi

IFS=$'\t' read -r KEY TITLE STATUS PHASE ASSIGNED_AGENT PRIORITY <<< "$TASK_ROW"

OWNER_PENDING="$(psql_scalar "SELECT count(*) FROM tasks WHERE status IN ('WAITING_OWNER_ACCEPTANCE','NEEDS_REVISION','QA_FAILED','BLOCKED');")"
ACTIVE_CLIENT="$(psql_scalar "SELECT count(*) FROM tasks WHERE (task_key LIKE 'CLIENT-%' OR task_key LIKE 'TASK-%') AND status IN ('TODO','IN_PROGRESS','WAITING_OWNER_ACCEPTANCE','NEEDS_REVISION','QA_FAILED','BLOCKED');")"

echo "# Autonomous Codex Dispatcher Hook"
echo "- Agent: $AGENT_KEY"
echo "- Task: $KEY"
echo "- Title: $TITLE"
echo "- Status: $STATUS"
echo "- Phase: $PHASE"
echo "- Assigned agent: $ASSIGNED_AGENT"
echo "- Priority: $PRIORITY"
echo "- Mode: $MODE"
echo "- Owner pending: $OWNER_PENDING"
echo "- Active client work: $ACTIVE_CLIENT"

if [[ "$KEY" != INTERNAL-* ]]; then
  echo "SKIP: only INTERNAL-* tasks are eligible."
  exit 0
fi

if [ "$STATUS" != "IN_PROGRESS" ]; then
  echo "SKIP: task must be IN_PROGRESS."
  exit 0
fi

if [ "$ASSIGNED_AGENT" != "$AGENT_KEY" ]; then
  echo "SKIP: task is assigned to $ASSIGNED_AGENT, not $AGENT_KEY."
  exit 0
fi

if [ "$OWNER_PENDING" -gt 0 ]; then
  echo "SKIP: Owner attention is required."
  exit 0
fi

if [ "$ACTIVE_CLIENT" -gt 0 ]; then
  echo "SKIP: active client work exists."
  exit 0
fi

PLAN_OUT="company/reports/ops/codex-dispatcher/$(date +%F)-${TASK_KEY}-plan.md"

if [ -f "$PLAN_OUT" ] && [ "${AI_COMPANY_FORCE_CODEX_PLAN:-0}" != "1" ]; then
  echo "SKIP: Codex plan already exists:"
  echo "$PLAN_OUT"
  exit 0
fi

echo "Eligible for Codex plan:"
echo "$PLAN_OUT"

if [ "$MODE" = "--dry-run" ]; then
  echo "Dry-run only. No Codex call."
  exit 0
fi

if [ "${AI_COMPANY_ENABLE_CODEX_DISPATCHER:-0}" != "1" ]; then
  echo "SKIP: set AI_COMPANY_ENABLE_CODEX_DISPATCHER=1 to run Codex plan."
  exit 0
fi

{
  echo "# Codex Dispatcher Plan: $TASK_KEY"
  echo
  echo "Generated at: $(date)"
  echo "Agent: $AGENT_KEY"
  echo
  ./runners/codex_task_plan.sh "$AGENT_KEY" "$TASK_KEY"
} | tee "$PLAN_OUT"

./runners/update_task_status.sh \
  "$TASK_KEY" \
  IN_PROGRESS \
  "Codex plan generated by autonomous dispatcher hook. Plan: $PLAN_OUT"

./runners/update_agent_runtime_status.sh \
  "$AGENT_KEY" \
  planning \
  "$TASK_KEY" \
  engineering_room \
  "Codex plan generated for $TASK_KEY."

./runners/log_event.sh \
  internal-ai-company-os \
  "$TASK_KEY" \
  "$AGENT_KEY" \
  codex_plan_generated \
  IN_PROGRESS \
  engineering_room \
  "Codex dispatcher plan generated" \
  "Plan written to $PLAN_OUT"

echo
echo "Codex dispatcher hook completed:"
echo "$PLAN_OUT"
