#!/usr/bin/env bash
set -euo pipefail

PROJECT_KEY="${1:-}"
TASK_KEY="${2:-}"
TITLE="${3:-}"
DESCRIPTION="${4:-}"
PRIORITY="${5:-MEDIUM}"
ASSIGNED_AGENT_KEY="${6:-engineer_agent}"
CURRENT_PHASE="${7:-IMPLEMENTATION}"

ROOT_DIR="/opt/ai-company"
PROJECT_DIR="$ROOT_DIR/projects/clients/$PROJECT_KEY"
TASK_FILE="$PROJECT_DIR/$TASK_KEY.md"

if [ -z "$PROJECT_KEY" ] || [ -z "$TASK_KEY" ] || [ -z "$TITLE" ] || [ -z "$DESCRIPTION" ]; then
  echo "Usage: ./runners/create_task.sh <project_key> <task_key> <title> <description> [priority] [assigned_agent_key] [current_phase]"
  exit 1
fi

if ! [[ "$PROJECT_KEY" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
  echo "ERROR: project_key must use lowercase letters, numbers, and dashes only."
  exit 1
fi

mkdir -p "$PROJECT_DIR"

if [ ! -f "$PROJECT_DIR/README.md" ]; then
  cat > "$PROJECT_DIR/README.md" << README
# $PROJECT_KEY

Client project workspace generated by AI Company OS.

## Project Key

$PROJECT_KEY

## Status

Created from AI Company OS task runner.
README
fi

if [ ! -f "$PROJECT_DIR/AGENT_HANDOVER.md" ]; then
  cat > "$PROJECT_DIR/AGENT_HANDOVER.md" << HANDOVER
# Agent Handover: $PROJECT_KEY

This file tracks handover notes for agents working on this client project.
HANDOVER
fi

docker exec -i ai_company_postgres psql -U ai_company -d ai_company \
  -v project_key="$PROJECT_KEY" \
  -v task_key="$TASK_KEY" \
  -v title="$TITLE" \
  -v description="$DESCRIPTION" \
  -v priority="$PRIORITY" \
  -v assigned_agent_key="$ASSIGNED_AGENT_KEY" \
  -v current_phase="$CURRENT_PHASE" <<'SQL'
INSERT INTO tasks (task_key, project_id, title, description, status, priority, assigned_agent_key, current_phase)
SELECT
  :'task_key',
  p.id,
  :'title',
  :'description',
  'TODO',
  :'priority',
  :'assigned_agent_key',
  :'current_phase'
FROM projects p
WHERE p.project_key = :'project_key'
ON CONFLICT (task_key) DO NOTHING;
SQL

cat > "$TASK_FILE" << TASK
# $TASK_KEY: $TITLE

## Project

$PROJECT_KEY

## Goal

$DESCRIPTION

## Assigned Agent

$ASSIGNED_AGENT_KEY

## Priority

$PRIORITY

## Current Phase

$CURRENT_PHASE

## Rules

- Work inside this project workspace unless explicitly instructed otherwise.
- Do not deploy production without owner approval.
- Do not access secrets.
- Do not use sudo unless the owner explicitly approves it.
- Update AGENT_HANDOVER.md with task notes.

## Required Output

- Work summary
- Files changed
- Test/build result
- Handover notes
TASK

./runners/log_event.sh \
  "$PROJECT_KEY" \
  "$TASK_KEY" \
  "$ASSIGNED_AGENT_KEY" \
  "task_created" \
  "TODO" \
  "planning_room" \
  "$TITLE" \
  "Task created: $DESCRIPTION"

echo "Task created:"
echo "- DB task: $TASK_KEY"
echo "- Task file: $TASK_FILE"
