#!/usr/bin/env bash
set -euo pipefail

PROJECT_KEY="${1:-}"
TASK_KEY="${2:-}"

if [[ -z "$PROJECT_KEY" || -z "$TASK_KEY" ]]; then
  echo "Usage:"
  echo "  ./runners/engineer_implementation_runner.sh <project_key> <engineer_task_key>"
  echo
  echo "Example:"
  echo "  ./runners/engineer_implementation_runner.sh client-company-profile-demo CLIENT-1-ENG-001"
  exit 1
fi

if ! [[ "$PROJECT_KEY" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
  echo "ERROR: project_key must use lowercase letters, numbers, and dashes only."
  exit 1
fi

if ! [[ "$TASK_KEY" =~ ^[A-Z0-9-]+$ ]]; then
  echo "ERROR: task_key must use uppercase letters, numbers, and dashes only."
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_DIR="$ROOT_DIR/projects/clients/$PROJECT_KEY"
TASK_FILE="$PROJECT_DIR/$TASK_KEY.md"
HANDOVER_FILE="$PROJECT_DIR/AGENT_HANDOVER.md"
SITE_DIR="$PROJECT_DIR/site"

SOURCE_ID="$(echo "$TASK_KEY" | sed -E 's/^CLIENT-([0-9]+)-.*/\1/')"
PM_TASK_KEY="CLIENT-${SOURCE_ID}-001"
PM_ANALYSIS_FILE="$PROJECT_DIR/PM_INTAKE_ANALYSIS-${PM_TASK_KEY}.md"

if [[ ! -d "$PROJECT_DIR" ]]; then
  echo "ERROR: project directory not found: $PROJECT_DIR"
  exit 1
fi

if [[ ! -f "$TASK_FILE" ]]; then
  echo "ERROR: engineer task file not found: $TASK_FILE"
  exit 1
fi

if [[ ! -f "$PM_ANALYSIS_FILE" ]]; then
  echo "ERROR: PM analysis file not found: $PM_ANALYSIS_FILE"
  exit 1
fi

mkdir -p "$SITE_DIR"

python3 - "$PROJECT_KEY" "$TASK_KEY" "$PM_TASK_KEY" "$PM_ANALYSIS_FILE" "$SITE_DIR" << 'PY'
from pathlib import Path
import html
import sys

project_key = sys.argv[1]
task_key = sys.argv[2]
pm_task_key = sys.argv[3]
pm_analysis_file = Path(sys.argv[4])
site_dir = Path(sys.argv[5])

analysis = pm_analysis_file.read_text()

requirement = "Client project generated from PM intake analysis."
capture = False
collected = []

for line in analysis.splitlines():
    if line.strip() == "## Requirement Summary":
        capture = True
        continue
    if capture and line.startswith("## "):
        break
    if capture:
        collected.append(line)

cleaned = "\n".join(collected).strip()
if cleaned:
    requirement = cleaned.replace(">", "").strip()

escaped_requirement = html.escape(requirement)
title = "Client Company Profile Demo"

(site_dir / "index.html").write_text(f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header class="hero">
    <nav class="nav">
      <div class="brand">AI Company Client Demo</div>
      <a href="#contact" class="nav-cta">Contact</a>
    </nav>

    <section class="hero-content">
      <p class="eyebrow">Generated by AI Company OS</p>
      <h1>Modern Company Profile Website</h1>
      <p class="hero-copy">
        This v0 implementation was generated from the PM intake analysis and project upload context.
      </p>
      <div class="hero-actions">
        <a href="#services" class="button primary">View Services</a>
        <a href="#process" class="button secondary">See Process</a>
      </div>
    </section>
  </header>

  <main>
    <section class="panel" id="requirement">
      <p class="eyebrow">Requirement Source</p>
      <h2>Owner Requirement</h2>
      <p>{escaped_requirement}</p>
    </section>

    <section class="grid" id="services">
      <article class="card">
        <h3>Company Profile</h3>
        <p>Clear landing page structure for presenting services, brand value, and contact paths.</p>
      </article>
      <article class="card">
        <h3>Responsive Layout</h3>
        <p>Mobile-friendly static layout suitable for quick preview and future iteration.</p>
      </article>
      <article class="card">
        <h3>Client Intake Ready</h3>
        <p>Built as a starting point for QA review and owner/client revision.</p>
      </article>
    </section>

    <section class="panel" id="process">
      <p class="eyebrow">Delivery Process</p>
      <h2>From Requirement to Preview</h2>
      <ol class="steps">
        <li>Owner submits requirement through dashboard.</li>
        <li>PM analysis creates implementation direction.</li>
        <li>Engineer produces initial website output.</li>
        <li>QA verifies against requirement and uploaded assets.</li>
      </ol>
    </section>

    <section class="panel contact" id="contact">
      <p class="eyebrow">Next Step</p>
      <h2>Ready for QA Review</h2>
      <p>This implementation is ready for QA verification and owner feedback.</p>
    </section>
  </main>

  <footer>
    <span>Project: {html.escape(project_key)}</span>
    <span>Task: {html.escape(task_key)}</span>
    <span>Source: {html.escape(pm_task_key)}</span>
  </footer>

  <script src="app.js"></script>
</body>
</html>
""")

(site_dir / "styles.css").write_text("""* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: #07111f;
  color: #e5f0ff;
}

a {
  color: inherit;
  text-decoration: none;
}

.hero {
  min-height: 76vh;
  padding: 28px;
  background:
    radial-gradient(circle at top left, rgba(56, 189, 248, 0.24), transparent 34%),
    radial-gradient(circle at bottom right, rgba(163, 230, 53, 0.18), transparent 32%),
    linear-gradient(135deg, #07111f, #101f35);
}

.nav {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.brand {
  font-weight: 900;
  letter-spacing: 0.04em;
}

.nav-cta,
.button {
  border-radius: 999px;
  padding: 10px 16px;
  font-weight: 800;
}

.nav-cta,
.button.secondary {
  border: 1px solid rgba(226, 232, 240, 0.28);
}

.hero-content {
  max-width: 880px;
  margin: 112px auto 0;
}

.eyebrow {
  margin: 0 0 12px;
  color: #a3e635;
  font-size: 13px;
  font-weight: 900;
  letter-spacing: 0.14em;
  text-transform: uppercase;
}

h1 {
  margin: 0;
  max-width: 820px;
  font-size: clamp(44px, 8vw, 92px);
  line-height: 0.92;
}

h2 {
  margin: 0 0 16px;
  font-size: clamp(28px, 5vw, 52px);
}

h3 {
  margin: 0 0 10px;
  font-size: 24px;
}

.hero-copy {
  max-width: 620px;
  margin: 24px 0;
  color: #b6c8df;
  font-size: 19px;
  line-height: 1.7;
}

.hero-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}

.button.primary {
  background: #a3e635;
  color: #102000;
}

main {
  width: min(1120px, calc(100% - 32px));
  margin: 0 auto;
  padding: 52px 0;
}

.panel,
.card {
  border: 1px solid rgba(148, 163, 184, 0.2);
  border-radius: 28px;
  background: rgba(15, 23, 42, 0.72);
  box-shadow: 0 28px 80px rgba(0, 0, 0, 0.28);
}

.panel {
  margin-bottom: 24px;
  padding: 32px;
}

.panel p,
.card p,
.steps {
  color: #b6c8df;
  line-height: 1.7;
}

.grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 18px;
  margin-bottom: 24px;
}

.card {
  padding: 24px;
}

.steps {
  padding-left: 22px;
}

.contact {
  background: linear-gradient(135deg, rgba(56, 189, 248, 0.18), rgba(163, 230, 53, 0.12));
}

footer {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: 14px;
  padding: 26px;
  color: #7890aa;
  font-size: 13px;
}

@media (max-width: 760px) {
  .hero {
    padding: 20px;
  }

  .hero-content {
    margin-top: 76px;
  }

  .grid {
    grid-template-columns: 1fr;
  }
}
""")

(site_dir / "app.js").write_text("""console.log("AI Company OS client implementation preview loaded.");
""")

(site_dir / "README.md").write_text(f"""# Implementation Output

Project:

    {project_key}

Engineer task:

    {task_key}

Source PM task:

    {pm_task_key}

Output:

- index.html
- styles.css
- app.js

Preview:

Open `index.html` in a browser or serve this folder using a static file server.
""")
PY

node --check "$SITE_DIR/app.js"

python3 - "$HANDOVER_FILE" "$PROJECT_KEY" "$TASK_KEY" "$PM_ANALYSIS_FILE" "$SITE_DIR" << 'PY'
from pathlib import Path
import sys

handover_file = Path(sys.argv[1])
project_key = sys.argv[2]
task_key = sys.argv[3]
pm_analysis_file = sys.argv[4]
site_dir = sys.argv[5]

marker = f"\n## Engineer Implementation Completed for {task_key}\n"
text = handover_file.read_text() if handover_file.exists() else ""

if marker in text:
    text = text.split(marker)[0].rstrip() + "\n"

block = f"""
## Engineer Implementation Completed for {task_key}

Project:

    {project_key}

Output folder:

    {site_dir}

Source PM analysis:

    {pm_analysis_file}

Files created:

- site/index.html
- site/styles.css
- site/app.js
- site/README.md

Status:

- Initial implementation output created.
- Ready for QA review.
"""

handover_file.write_text(text.rstrip() + "\n\n" + block.strip() + "\n")
PY

"$ROOT_DIR/runners/log_event.sh" \
  "$PROJECT_KEY" \
  "$TASK_KEY" \
  "engineer_agent" \
  "engineer_implementation_completed" \
  "IMPLEMENTED" \
  "engineering_desk" \
  "Engineer implementation output created" \
  "Engineer implementation runner created initial site output for $TASK_KEY."

"$ROOT_DIR/runners/update_task_status.sh" \
  "$TASK_KEY" \
  "IMPLEMENTED" \
  "Engineer implementation runner created initial site output under projects/clients/${PROJECT_KEY}/site."

echo "Engineer implementation completed:"
echo "- Project: $PROJECT_KEY"
echo "- Task: $TASK_KEY"
echo "- Output: $SITE_DIR"
echo "- PM analysis: $PM_ANALYSIS_FILE"
