#!/usr/bin/env bash
set -euo pipefail

PROJECT_KEY="${1:-}"
QA_TASK_KEY="${2:-}"

if [[ -z "$PROJECT_KEY" || -z "$QA_TASK_KEY" ]]; then
  echo "Usage:"
  echo "  ./runners/submit_project_to_owner_review.sh <project_key> <qa_task_key>"
  echo
  echo "Example:"
  echo "  ./runners/submit_project_to_owner_review.sh client-company-profile-demo CLIENT-1-QA-001"
  exit 1
fi

if ! [[ "$PROJECT_KEY" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
  echo "ERROR: project_key must use lowercase letters, numbers, and dashes only."
  exit 1
fi

if ! [[ "$QA_TASK_KEY" =~ ^[A-Z0-9-]+$ ]]; then
  echo "ERROR: qa_task_key must use uppercase letters, numbers, and dashes only."
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_DIR="$ROOT_DIR/projects/clients/$PROJECT_KEY"
HANDOVER_FILE="$PROJECT_DIR/AGENT_HANDOVER.md"
SITE_DIR="$PROJECT_DIR/site"
QA_REPORT_FILE="$PROJECT_DIR/QA_REPORT-$QA_TASK_KEY.md"

SOURCE_ID="$(echo "$QA_TASK_KEY" | sed -E 's/^CLIENT-([0-9]+)-.*/\1/')"
REVIEW_TASK_KEY="CLIENT-${SOURCE_ID}-REVIEW-001"
REVIEW_FILE="$PROJECT_DIR/$REVIEW_TASK_KEY.md"

if [[ ! -d "$PROJECT_DIR" ]]; then
  echo "ERROR: project directory not found: $PROJECT_DIR"
  exit 1
fi

if [[ ! -f "$QA_REPORT_FILE" ]]; then
  echo "ERROR: QA report not found: $QA_REPORT_FILE"
  exit 1
fi

if [[ ! -d "$SITE_DIR" ]]; then
  echo "ERROR: implementation output folder not found: $SITE_DIR"
  exit 1
fi

psql_scalar() {
  docker exec -i ai_company_postgres psql \
    -U ai_company \
    -d ai_company \
    -t \
    -A \
    -v ON_ERROR_STOP=1 \
    -c "$1"
}

psql_exec() {
  docker exec -i ai_company_postgres psql \
    -U ai_company \
    -d ai_company \
    -v ON_ERROR_STOP=1 \
    -c "$1"
}

QA_STATUS="$(psql_scalar "SELECT status FROM tasks WHERE task_key = '${QA_TASK_KEY}' LIMIT 1;")"

if [[ "$QA_STATUS" != "QA_PASSED" ]]; then
  echo "ERROR: QA task must be QA_PASSED before owner review submission."
  echo "- QA task: $QA_TASK_KEY"
  echo "- Current status: ${QA_STATUS:-not_found}"
  exit 1
fi

REVIEW_DESCRIPTION="Owner review submission for QA-passed client project.

Project: ${PROJECT_KEY}
QA task: ${QA_TASK_KEY}
QA report: ${QA_REPORT_FILE}
Implementation output: ${SITE_DIR}

Owner action required:
- Review implementation output
- Review QA report
- Choose ACCEPT, REVISE, or REJECT"

EXISTING_REVIEW="$(psql_scalar "SELECT task_key FROM tasks WHERE task_key = '${REVIEW_TASK_KEY}' LIMIT 1;")"

echo "# Submit Project to Owner Review"
echo "- Project: $PROJECT_KEY"
echo "- QA task: $QA_TASK_KEY"
echo "- Review task: $REVIEW_TASK_KEY"
echo "- QA report: $QA_REPORT_FILE"
echo "- Output: $SITE_DIR"

if [[ -z "$EXISTING_REVIEW" ]]; then
  "$ROOT_DIR/runners/create_task.sh" \
    "$PROJECT_KEY" \
    "$REVIEW_TASK_KEY" \
    "Owner review for ${PROJECT_KEY}" \
    "$REVIEW_DESCRIPTION" \
    HIGH \
    owner \
    owner_review
else
  echo "Review task already exists: $REVIEW_TASK_KEY"
fi

psql_exec "
UPDATE tasks
SET
  status = 'WAITING_OWNER_ACCEPTANCE',
  assigned_agent_key = 'owner',
  updated_at = now()
WHERE task_key = '${REVIEW_TASK_KEY}';
"

cat > "$REVIEW_FILE" << REVIEW
# $REVIEW_TASK_KEY: Owner Review for $PROJECT_KEY

## Project

$PROJECT_KEY

## Review Status

WAITING_OWNER_ACCEPTANCE

## QA Task

$QA_TASK_KEY

## QA Report

$QA_REPORT_FILE

## Implementation Output

$SITE_DIR

## Files to Review

- site/index.html
- site/styles.css
- site/app.js
- site/README.md
- QA_REPORT-$QA_TASK_KEY.md

## Owner Decision Needed

Choose one:

- ACCEPT
- REVISE
- REJECT

## Suggested Acceptance Criteria

- Output matches the owner/client requirement.
- QA report is acceptable.
- No blocking issue remains.
- Project can move to accepted/completed state.

## Notes

This review task was generated by:

    runners/submit_project_to_owner_review.sh
REVIEW

python3 - "$HANDOVER_FILE" "$PROJECT_KEY" "$QA_TASK_KEY" "$REVIEW_TASK_KEY" "$QA_REPORT_FILE" "$SITE_DIR" << 'PY'
from pathlib import Path
import sys

handover_file = Path(sys.argv[1])
project_key = sys.argv[2]
qa_task_key = sys.argv[3]
review_task_key = sys.argv[4]
qa_report_file = sys.argv[5]
site_dir = sys.argv[6]

marker = f"\n## Submitted to Owner Review: {review_task_key}\n"
text = handover_file.read_text() if handover_file.exists() else ""

if marker in text:
    text = text.split(marker)[0].rstrip() + "\n"

block = f"""
## Submitted to Owner Review: {review_task_key}

Project:

    {project_key}

QA task:

    {qa_task_key}

QA report:

    {qa_report_file}

Implementation output:

    {site_dir}

Review task:

    {review_task_key}

Status:

    WAITING_OWNER_ACCEPTANCE

Next step:

- Owner should review the implementation and QA report.
- Owner can ACCEPT, request REVISE, or REJECT.
"""

handover_file.write_text(text.rstrip() + "\n\n" + block.strip() + "\n")
PY

"$ROOT_DIR/runners/log_event.sh" \
  "$PROJECT_KEY" \
  "$REVIEW_TASK_KEY" \
  "owner" \
  "submitted_to_owner_review" \
  "WAITING_OWNER_ACCEPTANCE" \
  "owner_inbox" \
  "Project submitted to Owner review" \
  "QA-passed project ${PROJECT_KEY} submitted to owner review as ${REVIEW_TASK_KEY}."

echo
echo "Owner review submitted:"
docker exec -i ai_company_postgres psql -U ai_company -d ai_company -P pager=off -c "SELECT task_key, title, status, assigned_agent_key, current_phase FROM tasks WHERE task_key = '${REVIEW_TASK_KEY}';"
